var statuts = [
    "Actif",
    "Inactif",
    "En ligne",
    "Hors ligne",
    "Occupé",
    "Disponible",
    "Absent",
    "En congé",
    "En attente",
    "Nouvel utilisateur",
    "Utilisateur vérifié",
    "Utilisateur non vérifié",
    "Banni",
    "Suspendu",
    "Utilisateur premium",
    "Utilisateur régulier",
    "Utilisateur invité",
    "Utilisateur administrateur",
    "Utilisateur modérateur",
    "Utilisateur autorisé",
    "Utilisateur restreint",
    "Utilisateur bloqué",
    "Utilisateur en attente d'approbation",
    "Utilisateur en cours de validation",
    "Utilisateur désactivé",
    "Utilisateur en probation",
    "Utilisateur expiré",
    "Utilisateur supprimé",
    "Utilisateur en période d'essai",
    "Utilisateur actif avec restrictions",
    "Utilisateur inactif depuis longtemps"
  ];
export default  statuts; 